// The public surface of the data layer. No unscoped escape hatch is
// exported — if a future prompt needs cross-tenant access it will add an
// explicitly named function then.
export { forTenant, getRootTenant } from "./scoped";
export {
  createFact,
  confirmFact,
  retireFact,
  recordDecision,
  setPhaseStatus,
  createReminder,
  createDocument,
  CitationRequiredError,
  RationaleRequiredError,
  DomainRuleError,
} from "./domain";
export {
  slugify,
  createClient,
  updateClient,
  deleteClient,
  createProject,
  setProjectStatus,
  updateProjectSummary,
  deleteProject,
  addPhase,
  renamePhase,
  setPhaseVisibility,
  movePhase,
  deletePhase,
  addMilestone,
  setMilestoneDone,
  deleteMilestone,
  NotFoundError,
} from "./studio";
export {
  MAX_FILE_BYTES,
  ALLOWED_MIME,
  sanitizeFilename,
  assertUploadAllowed,
  buildObjectKey,
  prepareUpload,
  registerUpload,
  renameDocument,
  deleteDocument,
  documentUrl,
} from "./files";
export {
  createIntakeForm,
  updateIntakeForm,
  addIntakeItem,
  updateIntakeItem,
  deleteIntakeItem,
  moveIntakeItem,
  openIntakeForm,
  closeIntakeForm,
  deleteIntakeForm,
  deleteIntakeResponse,
  resolveIntakeToken,
  publicIntakeItems,
  presignIntakeUpload,
  submitIntake,
} from "./intake";
export {
  createNoteCapture,
  createVoiceCapture,
  tick,
  processCapture,
  validateProposals,
  retryCapture,
  proposedFactCount,
  discardProposedFact,
  editProposedFact,
  unretireFact,
} from "./captures";
